### 멤버 생성-v1
POST http://localhost:8080/api/v1/members
Content-Type: application/json

{
    "name": "hello"
}

### 멤버 생성-v2
POST http://localhost:8080/api/v2/members
Content-Type: application/json

{
    "name": "hello2"
}